'use client';

import {
  AirplaneTilt,
  Armchair,
  Baby,
  Bank,
  Barbell,
  Bed,
  BeerBottle,
  Bicycle,
  BookOpenText,
  Brain,
  Briefcase,
  Broom,
  Bus,
  Car,
  Certificate,
  ChargingStation,
  ChartLineUp,
  Church,
  Cloud,
  Coffee,
  Coins,
  Confetti,
  Cookie,
  CreditCard,
  Desktop,
  DeviceMobile,
  DotsThreeCircle,
  Drop,
  Eye,
  FileText,
  FilmSlate,
  FirstAid,
  Flame,
  ForkKnife,
  GameController,
  GasPump,
  Gavel,
  Gift,
  Globe,
  GraduationCap,
  Hamburger,
  Hammer,
  HandHeart,
  Handshake,
  Hospital,
  House,
  IdentificationCard,
  Key,
  Laptop,
  Lightning,
  LinkSimple,
  MapTrifold,
  Martini,
  Megaphone,
  MusicNotes,
  Newspaper,
  Package,
  Palette,
  PawPrint,
  Pencil,
  Percent,
  Person,
  PersonSimpleTaiChi,
  PiggyBank,
  Pill,
  Receipt,
  RoadHorizon,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sneaker,
  SoccerBall,
  Sparkle,
  SuitcaseRolling,
  Television,
  Ticket,
  Tooth,
  Translate,
  Truck,
  TShirt,
  UsersThree,
  Watch,
  WifiHigh,
  Wrench,
  type IconProps,
} from '@phosphor-icons/react';
import type { ComponentType } from 'react';
import type { CategoryIconId } from './finance-domain';

export const CATEGORY_ICON_MAP: Record<CategoryIconId, ComponentType<IconProps>> = {
  'fork-knife': ForkKnife,
  'shopping-cart': ShoppingCart,
  coffee: Coffee,
  package: Package,
  hamburger: Hamburger,
  cookie: Cookie,
  'beer-bottle': BeerBottle,
  briefcase: Briefcase,
  house: House,
  key: Key,
  bank: Bank,
  receipt: Receipt,
  lightning: Lightning,
  drop: Drop,
  flame: Flame,
  wifi: WifiHigh,
  'device-mobile': DeviceMobile,
  broom: Broom,
  hammer: Hammer,
  armchair: Armchair,
  car: Car,
  bus: Bus,
  'gas-pump': GasPump,
  'charging-station': ChargingStation,
  road: RoadHorizon,
  wrench: Wrench,
  shield: ShieldCheck,
  'credit-card': CreditCard,
  bicycle: Bicycle,
  'shopping-bag': ShoppingBag,
  't-shirt': TShirt,
  sneaker: Sneaker,
  laptop: Laptop,
  sparkle: Sparkle,
  scissors: Scissors,
  watch: Watch,
  'first-aid': FirstAid,
  pill: Pill,
  hospital: Hospital,
  tooth: Tooth,
  eye: Eye,
  barbell: Barbell,
  brain: Brain,
  wellness: PersonSimpleTaiChi,
  users: UsersThree,
  baby: Baby,
  coins: Coins,
  person: Person,
  'paw-print': PawPrint,
  'graduation-cap': GraduationCap,
  book: BookOpenText,
  pencil: Pencil,
  certificate: Certificate,
  translate: Translate,
  film: FilmSlate,
  television: Television,
  'game-controller': GameController,
  ticket: Ticket,
  palette: Palette,
  'soccer-ball': SoccerBall,
  martini: Martini,
  music: MusicNotes,
  airplane: AirplaneTilt,
  bed: Bed,
  map: MapTrifold,
  'identification-card': IdentificationCard,
  suitcase: SuitcaseRolling,
  cloud: Cloud,
  globe: Globe,
  newspaper: Newspaper,
  link: LinkSimple,
  percent: Percent,
  'file-text': FileText,
  gavel: Gavel,
  'piggy-bank': PiggyBank,
  'chart-line': ChartLineUp,
  desktop: Desktop,
  megaphone: Megaphone,
  truck: Truck,
  handshake: Handshake,
  gift: Gift,
  'hand-heart': HandHeart,
  church: Church,
  confetti: Confetti,
  dots: DotsThreeCircle,
};

export const CUSTOM_CATEGORY_ICON_IDS: readonly CategoryIconId[] = [
  'sparkle', 'gift', 'hand-heart', 'paw-print', 'baby', 'users',
  'house', 'car', 'bicycle', 'airplane', 'fork-knife', 'coffee', 'shopping-bag', 'briefcase',
  'graduation-cap', 'book', 'music', 'film', 'game-controller', 'palette', 'soccer-ball',
  'first-aid', 'barbell', 'cloud', 'globe', 'desktop', 'wrench', 'church', 'dots',
];

export function CategoryIcon({ icon, ...props }: { icon: CategoryIconId } & IconProps) {
  const Icon = CATEGORY_ICON_MAP[icon];
  return <Icon {...props} />;
}
